### ISSUE TITLE
*** stack smashing detected***: python terminated

### ISSUE THREAD

**Issue by TimothyBergstrom** [statisticalbiotechnology/quandenser-pipeline#5]
Sometimes when running on a computer with nvidia drivers locally, this error message will be shown. Usually, it stabilizes after a couple of runs. I've been trying to find the cause of this bug, but it seems to be correlated to the creation of the GUI window through Singularity. Running the GUI with pdb prevent the bug from happening for some reason when initiating the GUI. There are several recursive functions in the GUI, but disabling them does not affect the stack smashing problem

If you have any ideas about the bug, please let me know!

**Comment by TimothyBergstrom** [comment]
I managed to get out an error message from the crashing, I think.
```

*** stack smashing detected ***: python terminated                                                                                                                                       
Aborted (core dumped)                                                                                                                                                                    
SIGABRT: abort                                                                                                                                                                           
PC=0x473cbb m=0 sigcode=0                                                                                                                                                                
                                                                                                                                                                                         
goroutine 1 [running, locked to thread]:                                                                                                                                                 
syscall.RawSyscall(0x3e, 0x43c0, 0x6, 0x0, 0xc0001cbef0, 0x49e0d2, 0x43c0)                                                                                                               
        /usr/local/go/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001cbeb8 sp=0xc0001cbeb0 pc=0x473cbb                                                                                 
syscall.Kill(0x43c0, 0x6, 0x43892e, 0xc0001cbf20)                                                                                                                                        
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001cbf00 sp=0xc0001cbeb8 pc=0x47062b
github.com/sylabs/singularity/internal/app/starter.Master.func2()
        internal/app/starter/master_linux.go:156 +0x3e fp=0xc0001cbf38 sp=0xc0001cbf00 pc=0x73b34e
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
        internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001cbf60 sp=0xc0001cbf38 pc=0x739b5f
main.main()
        cmd/starter/main_linux.go:106 +0x5f fp=0xc0001cbf98 sp=0xc0001cbf60 pc=0x91e0af
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0001cbfe0 sp=0xc0001cbf98 pc=0x430bd7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0001cbfe8 sp=0xc0001cbfe0 pc=0x45c6f1

goroutine 5 [syscall]:
os/signal.signal_recv(0xafc2a0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002e4190)
        internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x8, 0x4, 0x43d3, 0xc00000cb60)
        internal/app/starter/master_linux.go:155 +0x405
main.startup()
        cmd/starter/main_linux.go:75 +0x43b
created by main.main
        cmd/starter/main_linux.go:102 +0x35
rax    0x0
rbx    0x0
rcx    0x473cbb
rdx    0x0
rdi    0x43c0
rsi    0x6
rbp    0xc0001cbef0
rsp    0xc0001cbeb0
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0xc
r13    0xff
r14    0xaf111c
r15    0x0
rip    0x473cbb
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```
